# Site settings
title: S2TsVPb's Homepage
email: xuyixuan3236@126.com
description: >-
  欢迎来到S2TsVPb的主页，一片爱与自由的原野。
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://s2tsvpb.github.io" # the base hostname & protocol for your site
github_username: S2TsVPb
author: S2TsVPb
lang: zh-CN
timezone: Asia/Shanghai

# Build settings
theme: minima

plugins:
  - jekyll-feed
  - jekyll-sitemap

header_pages:
  - about.markdown   # 关于我页面
  - search.md        # 搜索页面
